name: "Test docker-compose-core.yaml"
on:
  push:
    branches:
      - "**"
jobs:
  test_core:
    strategy:
      matrix:
        include:
          - compose_args: "-f docker-compose-core.yaml"
            run_e2e_tests: false
            directory: ""
          - compose_args: "-f docker-compose-core.yaml"
            run_e2e_tests: false
            directory: "docker-compose/camunda-8.6"
    uses: ./.github/workflows/template-deploy.yaml
    name: Test deploying from directory "${{ matrix.directory || 'root' }}"
    secrets: inherit
    with:
      compose_args: ${{ matrix.compose_args }}
      run_e2e_tests: ${{ matrix.run_e2e_tests }}
      directory: ${{ matrix.directory }}

