name: Test Camunda (Elasticsearch)

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4

    - name: "Run application"
      run: |
        docker compose -f docker-compose.yaml up -d
